sudo: false
language: node_js
node_js: 
  - "node"
cache: yarn

script:
  - yarn run build
  - yarn run test:unit

before_deploy:
  - yarn run docs
  - mkdir public
  - mv docs public/docs
  - mv dist public/dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master