sudo: false
language: node_js
node_js: 
  - "node"
cache: yarn

script:
  - yarn run build
  - yarn run test:unit

before_deploy:
  # We need to override the publicPath because docs serves from a sub-directory
  - echo 'module.exports = {"publicPath":"/io-callisto/dist/"}' >> vue.config.js
  - yarn run build
  - yarn run docs
  - mkdir pages
  - mv docs pages/docs
  - mv dist pages/dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: pages
  on:
    branch: master